service: sls-rbi-homework

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, env:NODE_ENV}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}

plugins:
  - serverless-offline

package:
  include: "*"

functions:
  menu:
    description: Called to create an order in NCR.
    handler: dist/index.menuHandler
    events:
      - http:
          path: menu
          method: GET
          async: true
  cart:
    description: Get Cart information
    handler: dist/index.cartHandler
    events:
      - http:
          path: cart
          method: GET
          async: true
  calorieCounter:
    description: Get Calories information
    handler: dist/index.calorieCounterHandler
    events:
      - http:
          path: /{menuItem}/calories/
          method: GET
          request:
            parameters:
              paths:
                menuItem: true
          async: true
